#!/bin/bash

#Colours
greenColour="\e[0;32m\033[1m"
endColour="\033[0m\e[0m"
redColour="\e[0;31m\033[1m"
blueColour="\e[0;34m\033[1m"
yellowColour="\e[0;33m\033[1m"
purpleColour="\e[0;35m\033[1m"
turquoiseColour="\e[0;36m\033[1m"
grayColour="\e[0;37m\033[1m"

# Función para manejar la señal SIGINT (Ctrl+C)
handle_sigint() {
    echo -e "\n\n${redColour}Script interrumpido por Ctrl+C\n\nSaliendo...\n${endColour}"
    tput cnorm == exit 1
}

# Atrapar la señal SIGINT y llamar a la función handle_sigint
trap handle_sigint SIGINT

FORMAT="^([0-9]{1,3}\.){3}[0-9]{1,3}/([0-9]|[1-2][0-9]|3[0-2])$"
IPCIDR="$1"

if [[ $1 =~ $FORMAT ]];then
IP="$(echo "$1" | sed 's/\// /' | awk '{print $1}')"
CIDR="$(echo "$1" | sed 's/\// /' | awk '{print $2}')"
HOSTS="$(echo "(2^(32-${CIDR}))" | bc)"
GWBIN=$(( 0xffffffff ^ ((1 << (32 - $CIDR)) -1)))
GW=$(echo "$((($GWBIN >> 24) & 0xff)).$((($GWBIN >> 16) & 0xff)).$((($GWBIN >> 8) & 0xff)).$(($GWBIN & 0xff))")
WC=$(echo "$(((~($GWBIN) >> 24) & 0xff)).$(((~($GWBIN) >> 16) & 0xff)).$(((~($GWBIN) >> 8) & 0xff)).$((~($GWBIN) & 0xff))")

IFS=. read -r i1 i2 i3 i4 <<< "$IP"
IFS=. read -r m1 m2 m3 m4 <<< "$GW"
FIP=$(echo "$((i1 & m1))"."$((i2 & m2))"."$((i3 & m3))"."$((i4 & m4))")
LIP=$(echo "$((i1 | ~m1 & 255))"."$((i2 | ~m2 & 255))"."$((i3 | ~m3 & 255))"."$((i4 | ~m4 & 255))")

echo -e "\n${blueColour}La IP es:${endColour} ${greenColour}$IP${endColour}\n\n${blueColour}El CIDR es:${endColour} ${greenColour}$CIDR${endColour}\n\n${blueColour}Total hosts:${endColour} ${greenColour}$HOSTS${endColour}\n\n${blueColour}Max hosts:${endColour} ${greenColour}$((${HOSTS}-2))${endColour}\n\n${blueColour}La mascara de red es:${endColour} ${greenColour}$GW${endColour}\n\n${blueColour}La wildcard es:${endColour} ${greenColour}$WC${endColour}\n\n${blueColour}La Network ID es:${endColour} ${greenColour}$FIP${endColour}\n\n${blueColour}La broadcast adress es:${endColour} ${greenColour}$LIP${endColour}\n"
else

  echo -e "\n${redColour}$1${endColour} ${yellowColour}no se corresponde con una direccion IP en formato CIDR.${endColour}\n"
fi
